#4. Implementa un algoritmo en Python para calcular el perímetro de un rectángulo, conociendo su base y altura. Los datos se deben almacenar en variables, y el resultado se debe mostrar en pantalla. 
# perímetro = 2 * (base + altura) 

base = float(input('Ingresa la base de tu rectangulo: '))
altura = float(input('Ingresa la altura de tu rectangulo: '))
perimetro = 2 * (base + altura)

print('El perimetro de tu rectangulo es:', perimetro)